// AUTO-GENERATED by better-intl. Do not edit by hand.
// Regenerated automatically by the Next.js plugin on dev/build.

/* eslint-disable */
import { createI18n } from "better-intl/runtime";

export const translations = {
	en: {
		app: {
			metadata: {
				title: "cd/ui · lightweight, accessible React components",
				description: "Accessible React components built with Base UI and Tailwind CSS v4. Build-measured bundle size, installed as source code with the shadcn CLI.",
			},
			locale: {
				english: "English",
				portuguese: "Portuguese",
			},
		},
	},
	pt: {
		app: {
			metadata: {
				title: "cd/ui · componentes React leves e acessíveis",
				description: "Componentes React acessíveis com Base UI e Tailwind CSS v4. Tamanho medido no build, código instalado no seu projeto pelo shadcn CLI.",
			},
			locale: {
				english: "Inglês",
				portuguese: "Português",
			},
		},
	},
} as const;

export type Locale = keyof typeof translations;

/** Runtime config for `better-intl/runtime`, baked into the helpers below. */
export const intlConfig = {
	"defaultLocale": "en",
	"locales": [
		"en",
		"pt"
	],
	"storage": {
		"type": "cookie",
		"key": "locale"
	}
} as const;

// Helpers bound to `translations` + `intlConfig` once. Import `t` anywhere
// (sync on both client and server); call `setLocale()` once per request in the
// root layout; `getLocale()` returns the active locale string; call
// `updateLocale(locale)` to persist a new preference.
const i18n = createI18n(translations, intlConfig);
export const { t, setLocale, getLocale, updateLocale } = i18n;
